<?php

namespace Compo\DepartmentBundle\Repository;

/**
 * CollaboratorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DepartmentRepository extends \Doctrine\ORM\EntityRepository
{

}
