<?php

namespace Compo\CollaboratorBundle\Repository;

/**
 * CollaboratorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CollaboratorRepository extends \Doctrine\ORM\EntityRepository
{

}
